//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TILab1WPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Criterion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Criterion()
        {
            this.Marks = new HashSet<Mark>();
        }
    
        public int CNum { get; set; }
        public string CName { get; set; }
        public int CRange { get; set; }
        public int CWeight { get; set; }
        public string CType { get; set; }
        public string OptimType { get; set; }
        public string EdIzmer { get; set; }
        public string ScaleType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mark> Marks { get; set; }
    }
}
