//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TILab1WPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vector
    {
        public int VNum { get; set; }
        public int ANum { get; set; }
        public int MNum { get; set; }
    
        public virtual Alternative Alternative { get; set; }
        public virtual Mark Mark { get; set; }
    }
}
