SET IDENTITY_INSERT [dbo].[Vectors] ON
INSERT INTO [dbo].[Vectors] ([VNum], [ANum], [MNum]) VALUES (1, 1, 2)
INSERT INTO [dbo].[Vectors] ([VNum], [ANum], [MNum]) VALUES (2, 1, 9)
INSERT INTO [dbo].[Vectors] ([VNum], [ANum], [MNum]) VALUES (3, 1, 12)
INSERT INTO [dbo].[Vectors] ([VNum], [ANum], [MNum]) VALUES (4, 1, 16)
INSERT INTO [dbo].[Vectors] ([VNum], [ANum], [MNum]) VALUES (5, 1, 25)
INSERT INTO [dbo].[Vectors] ([VNum], [ANum], [MNum]) VALUES (6, 2, 4)
INSERT INTO [dbo].[Vectors] ([VNum], [ANum], [MNum]) VALUES (7, 2, 7)
INSERT INTO [dbo].[Vectors] ([VNum], [ANum], [MNum]) VALUES (8, 2, 11)
INSERT INTO [dbo].[Vectors] ([VNum], [ANum], [MNum]) VALUES (9, 2, 19)
INSERT INTO [dbo].[Vectors] ([VNum], [ANum], [MNum]) VALUES (10, 2, 22)
INSERT INTO [dbo].[Vectors] ([VNum], [ANum], [MNum]) VALUES (11, 3, 1)
INSERT INTO [dbo].[Vectors] ([VNum], [ANum], [MNum]) VALUES (12, 3, 10)
INSERT INTO [dbo].[Vectors] ([VNum], [ANum], [MNum]) VALUES (13, 3, 12)
INSERT INTO [dbo].[Vectors] ([VNum], [ANum], [MNum]) VALUES (14, 3, 20)
INSERT INTO [dbo].[Vectors] ([VNum], [ANum], [MNum]) VALUES (15, 3, 21)
INSERT INTO [dbo].[Vectors] ([VNum], [ANum], [MNum]) VALUES (16, 4, 5)
INSERT INTO [dbo].[Vectors] ([VNum], [ANum], [MNum]) VALUES (17, 4, 8)
INSERT INTO [dbo].[Vectors] ([VNum], [ANum], [MNum]) VALUES (18, 4, 13)
INSERT INTO [dbo].[Vectors] ([VNum], [ANum], [MNum]) VALUES (19, 4, 18)
INSERT INTO [dbo].[Vectors] ([VNum], [ANum], [MNum]) VALUES (20, 4, 23)
INSERT INTO [dbo].[Vectors] ([VNum], [ANum], [MNum]) VALUES (21, 5, 3)
INSERT INTO [dbo].[Vectors] ([VNum], [ANum], [MNum]) VALUES (22, 5, 6)
INSERT INTO [dbo].[Vectors] ([VNum], [ANum], [MNum]) VALUES (23, 5, 15)
INSERT INTO [dbo].[Vectors] ([VNum], [ANum], [MNum]) VALUES (24, 5, 17)
INSERT INTO [dbo].[Vectors] ([VNum], [ANum], [MNum]) VALUES (25, 5, 24)
SET IDENTITY_INSERT [dbo].[Vectors] OFF
