SET IDENTITY_INSERT [dbo].[Marks] ON
INSERT INTO [dbo].[Marks] ([MNum], [CNum], [MName], [MRange], [NumMark], [NormMark]) VALUES (1, 1, N'Disastrous', 0, 1, 0)
INSERT INTO [dbo].[Marks] ([MNum], [CNum], [MName], [MRange], [NumMark], [NormMark]) VALUES (2, 1, N'Cringy', 0, 2, 0)
INSERT INTO [dbo].[Marks] ([MNum], [CNum], [MName], [MRange], [NumMark], [NormMark]) VALUES (3, 1, N'Decent', 0, 3, 0)
INSERT INTO [dbo].[Marks] ([MNum], [CNum], [MName], [MRange], [NumMark], [NormMark]) VALUES (4, 1, N'Nice', 0, 4, 0)
INSERT INTO [dbo].[Marks] ([MNum], [CNum], [MName], [MRange], [NumMark], [NormMark]) VALUES (5, 1, N'Perfect', 0, 5, 0)
INSERT INTO [dbo].[Marks] ([MNum], [CNum], [MName], [MRange], [NumMark], [NormMark]) VALUES (6, 2, N'Negative', 0, 1, 0)
INSERT INTO [dbo].[Marks] ([MNum], [CNum], [MName], [MRange], [NumMark], [NormMark]) VALUES (7, 2, N'Bad', 0, 2, 0)
INSERT INTO [dbo].[Marks] ([MNum], [CNum], [MName], [MRange], [NumMark], [NormMark]) VALUES (8, 2, N'Decent', 0, 3, 0)
INSERT INTO [dbo].[Marks] ([MNum], [CNum], [MName], [MRange], [NumMark], [NormMark]) VALUES (9, 2, N'Cool', 0, 4, 0)
INSERT INTO [dbo].[Marks] ([MNum], [CNum], [MName], [MRange], [NumMark], [NormMark]) VALUES (10, 2, N'Amazing', 0, 5, 0)
INSERT INTO [dbo].[Marks] ([MNum], [CNum], [MName], [MRange], [NumMark], [NormMark]) VALUES (11, 3, N'Cringy', 0, 1, 0)
INSERT INTO [dbo].[Marks] ([MNum], [CNum], [MName], [MRange], [NumMark], [NormMark]) VALUES (12, 3, N'Boring', 0, 2, 0)
INSERT INTO [dbo].[Marks] ([MNum], [CNum], [MName], [MRange], [NumMark], [NormMark]) VALUES (13, 3, N'Funny', 0, 3, 0)
INSERT INTO [dbo].[Marks] ([MNum], [CNum], [MName], [MRange], [NumMark], [NormMark]) VALUES (14, 3, N'Pro', 0, 4, 0)
INSERT INTO [dbo].[Marks] ([MNum], [CNum], [MName], [MRange], [NumMark], [NormMark]) VALUES (15, 3, N'Outstanding', 0, 5, 0)
INSERT INTO [dbo].[Marks] ([MNum], [CNum], [MName], [MRange], [NumMark], [NormMark]) VALUES (16, 4, N'Sto0ped', 0, 1, 0)
INSERT INTO [dbo].[Marks] ([MNum], [CNum], [MName], [MRange], [NumMark], [NormMark]) VALUES (17, 4, N'Bad', 0, 2, 0)
INSERT INTO [dbo].[Marks] ([MNum], [CNum], [MName], [MRange], [NumMark], [NormMark]) VALUES (18, 4, N'OK', 0, 3, 0)
INSERT INTO [dbo].[Marks] ([MNum], [CNum], [MName], [MRange], [NumMark], [NormMark]) VALUES (19, 4, N'Smart', 0, 4, 0)
INSERT INTO [dbo].[Marks] ([MNum], [CNum], [MName], [MRange], [NumMark], [NormMark]) VALUES (20, 4, N'Prodigy', 0, 5, 0)
INSERT INTO [dbo].[Marks] ([MNum], [CNum], [MName], [MRange], [NumMark], [NormMark]) VALUES (21, 5, N'Miserable', 0, 1, 0)
INSERT INTO [dbo].[Marks] ([MNum], [CNum], [MName], [MRange], [NumMark], [NormMark]) VALUES (22, 5, N'Fine', 0, 2, 0)
INSERT INTO [dbo].[Marks] ([MNum], [CNum], [MName], [MRange], [NumMark], [NormMark]) VALUES (23, 5, N'Average', 0, 3, 0)
INSERT INTO [dbo].[Marks] ([MNum], [CNum], [MName], [MRange], [NumMark], [NormMark]) VALUES (24, 5, N'Pro', 0, 4, 0)
INSERT INTO [dbo].[Marks] ([MNum], [CNum], [MName], [MRange], [NumMark], [NormMark]) VALUES (25, 5, N'Superstar', 0, 5, 0)
SET IDENTITY_INSERT [dbo].[Marks] OFF
